name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Указываем ветку, из которой будем развертывать

jobs:
  deploy:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем Node.js (если ваш проект использует npm)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Указываем версию Node.js

      # Шаг 3: Устанавливаем зависимости (если нужно)
      - name: Install dependencies
        run: |
          cd frontend  # Переходим в папку frontend
          npm install  # Устанавливаем зависимости

      # Шаг 4: Собираем проект (если нужно)
      - name: Build project
        run: |
          cd frontend  # Переходим в папку frontend
          npm run build  # Собираем проект

      # Шаг 5: Развертываем на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Токен для доступа к репозиторию
          publish_dir: frontend/dist  # Указываем папку для развертывания
